Repository MicrosoftDocs/winrt-api, pull requests merged in 2019-09, with the labels that each got.

#1217 Change default value to align with reality.
  windows.ui.composition/compositionradialgradientbrush_ellipseradius.md
Labels: assessing_(C&L), do-not-merge, review-team-triage

#1216 Fixing the default value to align with reality.
  windows.ui.composition/compositionradialgradientbrush_gradientoriginoffset.md
Labels: do-not-merge, review-team-triage

#1225 Fix broken link
  windows.ui.xaml.input/focusmanager_losingfocus.md
Labels: do-not-merge, review-team-triage

#1139 Make CallStateChanged event static
  windows.applicationmodel.calls/phonecallmanager_callstatechanged.md
Labels: PRRT required, assessing_(C&L), do-not-merge, review-team-triage

#1233 Attempt to fix broken xaml-islands link
  windows.ui.xaml.controls/contentdialog.md
Labels: do-not-merge, review-team-triage

#1230 Update uielement_transformtovisual_799251735.md
  windows.ui.xaml/uielement_transformtovisual_799251735.md
Labels: assessing_(C&L), do-not-merge, review-team-triage

#1232 Update gridunittype.md
  windows.ui.xaml/gridunittype.md
Labels: assessing_(C&L), do-not-merge, review-team-triage

#1231 Update uielement_arrange_958316931.md
  windows.ui.xaml/uielement_arrange_958316931.md
Labels: assessing_(C&L), do-not-merge, review-team-triage
