Repository MicrosoftDocs/winrt-api, pull requests merged in 2019-11, with the labels that each got.

#1305 StartReconnectingTransport should not be used by developers
  windows.networking.vpn/vpnchannel_startreconnectingtransport_767922886.md
Labels: do-not-merge

#1313 Update
  windows.ui.startscreen/jumplist.md
Labels: Change sent to author, assessing_(C&L), do-not-merge, uwp/prod, winrt-reference/tech

#1320 Fix Xaml syntax error
  windows.ui.xaml/frameworkelement_language.md
Labels: Change sent to author, assessing_(C&L), do-not-merge, uwp/prod, winrt-reference/tech

#1329 Clarify documentation by updating the path to kits
  windows.ui.xaml.controls/appbar.md
Labels: Change sent to author, assessing_(C&L), do-not-merge, uwp/prod, winrt-reference/tech

#1331 Fixed typo
  windows.ui.xaml.controls/progressbar.md
Labels: Change sent to author, do-not-merge, uwp/prod, winrt-reference/tech
