Repository MicrosoftDocs/winrt-api, pull requests merged in 2019-12, with the labels that each got.

#1336 Adding links to AppServiceTriggerDetails
  windows.applicationmodel.appservice/appserviceconnection.md
Labels: Change sent to author, assessing_(C&L), do-not-merge, uwp/prod, winrt-reference/tech

#1282 Remove StreamWebSocket from all UWP VPN documentation
  windows.networking.vpn/vpnchannel_addandassociatetransport_1590467618.md
Labels: Change sent to author, assessing_(C&L), do-not-merge

#1283 Remove StreamWebSocket from all UWP VPN documentation
  windows.networking.vpn/vpnchannel_associatetransport_841671883.md
Labels: Change sent to author, assessing_(C&L), do-not-merge

#1284 Remove StreamWebSocket from all UWP VPN documentation
  windows.networking.vpn/vpnchannel_replaceandassociatetransport_1938622656.md
Labels: Change sent to author, assessing_(C&L), do-not-merge

#1285 Remove StreamWebSocket from all UWP VPN documentation
  windows.networking.vpn/vpnchannel_startreconnectingtransport_767922886.md
Labels: Change sent to author, assessing_(C&L), do-not-merge

#1287 Use JumpListSystemGroupKind as property value
  windows.ui.startscreen/jumplist_systemgroupkind.md
Labels: Change sent to author, assessing_(C&L), do-not-merge

#1288 Add FontIcon.Glyph code-behind examples
  windows.ui.xaml.controls/fonticon.md
  windows.ui.xaml.controls/fonticon_glyph.md
Labels: Change sent to author, assessing_(C&L), do-not-merge, uwp/prod, winrt-reference/tech

#1352 Updated RichEditBox menu opening API doc
  windows.ui.xaml.controls/richeditbox_contextmenuopening.md
Labels: Change sent to author, assessing_(C&L), do-not-merge, uwp/prod, winrt-reference/tech

#1350 Updated ContextMenuOpening event page
  windows.ui.xaml.controls/textbox_contextmenuopening.md
Labels: Change sent to author, do-not-merge, uwp/prod, winrt-reference/tech

#1351 Updated TextBox API page
  windows.ui.xaml.controls/textbox.md
Labels: Change sent to author, assessing_(C&L), do-not-merge, uwp/prod, winrt-reference/tech

#1317 Update asymmetricalgorithmnames_ecdsap521sha512.md
  windows.security.cryptography.core/asymmetricalgorithmnames_ecdsap521sha512.md
Labels: Change sent to author, assessing_(C&L), do-not-merge, uwp/prod, winrt-reference/tech

#1318 Update asymmetricalgorithmnames_ecdsap521sha512.md
  windows.security.cryptography.core/asymmetricalgorithmnames_ecdsap521sha512.md
Labels: Change sent to author, assessing_(C&L), do-not-merge, uwp/prod, winrt-reference/tech
