Repository MicrosoftDocs/winrt-api, pull requests merged in 2019-06, with the labels that each got.

#1123 Fix links in Windows.UI.Input.GestureRecognizer
  windows.ui.input/gesturerecognizer_gesturerecognizer_1221375020.md
Labels: PRRT required

#1127 Remove duplicate links
  windows.networking.networkoperators/mobilebroadbandaccountwatcher_accountupdated.md
Labels: PRRT required

#1125 Remove duplicate links
  windows.storage/applicationdata_temporaryfolder.md
Labels: PRRT required

#1140 Fix small typo in Windows.Media.Core.VideoTrackSupportInfo.DecoderStatus
  windows.media.core/videotracksupportinfo_decoderstatus.md
Labels: PRRT required, do-not-merge, review-team-triage

#1101 Update bluetoothleappearance_fromparts_1479822747.md
  windows.devices.bluetooth/bluetoothleappearance_fromparts_1479822747.md
Labels: PRRT required

#1148 FindPackagesForUserWithPackageTypes uses empty string not null
  windows.management.deployment/packagemanager_findpackagesforuserwithpackagetypes_1110730286.md
Labels: do-not-merge, review-team-triage
