Repository MicrosoftDocs/winrt-api, pull requests merged in 2019-07, with the labels that each got.

#1151 Fix invalid reference to audio degradation in Windows.Media.Core.Vide…
  windows.media.core/videotrack_supportinfo.md
Labels: do-not-merge, review-team-triage

#1152 Remove duplication
  windows.storage/applicationdatacontainer.md
Labels: do-not-merge, review-team-triage

#1143 Fix misc typo in windows.gaming.input
  windows.gaming.input.forcefeedback/forcefeedbackloadeffectresult.md
  windows.gaming.input/arcadestick_arcadesticks.md
  windows.gaming.input/flightstick_flightsticks.md
  windows.gaming.input/gamepad_gamepadadded.md
  windows.gaming.input/gamepad_gamepads.md
  windows.gaming.input/racingwheel_racingwheels.md
  windows.gaming.input/rawgamecontroller_rawgamecontrollers.md
  windows.gaming.input/uinavigationcontroller_uinavigationcontrollers.md
Labels: do-not-merge, review-team-triage

#1111 Updated documentation to clarify SetFocusPoint's usage for different …
  windows.graphics.holographic/holographiccamerarenderingparameters_setfocuspoint_1040378076.md
  windows.graphics.holographic/holographiccamerarenderingparameters_setfocuspoint_1275160748.md
  windows.graphics.holographic/holographiccamerarenderingparameters_setfocuspoint_184506220.md
Labels: PRRT required

#1156 Update datatemplateselector_selecttemplatecore_711611086.md
  windows.ui.xaml.controls/datatemplateselector_selecttemplatecore_711611086.md
Labels: assessing (C&L), do-not-merge, review-team-triage

#1175 Update description of smsfilteractiontype.md to include restriction for AcceptImmediately action type
  windows.devices.sms/smsfilteractiontype.md
Labels: assessing (C&L), do-not-merge, review-team-triage

#1182 Drewbatgit patch 1179
  windows.media.audio/audiograph_createframeoutputnode_1505747890.md
  windows.media.audio/audiograph_createframeoutputnode_1936992142.md
Labels: do-not-merge

#1181 Update smsfilteractiontype.md
  windows.devices.sms/smsfilteractiontype.md
Labels: assessing (C&L), do-not-merge, review-team-triage

#1188 Remove XML comment
  windows.ui.xaml/frameworkelement_setbinding_28713777.md
Labels: assessing (C&L), do-not-merge, review-team-triage
