Repository MicrosoftDocs/winrt-api, pull requests merged in 2019-10, with the labels that each got.

#1247 Include info on which XML this accepts and when
  windows.networking.vpn/vpnmanagementagent_addprofilefromxmlasync_1803908060.md
Labels: assessing_(C&L), do-not-merge, review-team-triage

#1246 update activity.md
  windows.applicationmodel.useractivities/useractivity.md
Labels: assessing_(C&L), do-not-merge, review-team-triage

#1248 Fix Language description for IMediaTrack/AudioTrack/VideoTrack
  windows.media.core/audiotrack_id.md
  windows.media.core/audiotrack_language.md
  windows.media.core/imediatrack_language.md
  windows.media.core/sceneanalysiseffect_highdynamicrangeanalyzer.md
  windows.media.core/videotrack_id.md
  windows.media.core/videotrack_language.md
Labels: do-not-merge, review-team-triage

#1253 Update itextparagraphformat_widowcontrol.md
  windows.ui.text/itextparagraphformat_widowcontrol.md
Labels: do-not-merge, review-team-triage

#668 Update videoframe_type.md
  windows.media/videoframe_type.md
Labels: assessing_(C&L)

#1252 Update connectivitymanager_addhttproutepolicy_1422666154.md
  windows.networking.connectivity/connectivitymanager_addhttproutepolicy_1422666154.md
Labels: assessing_(C&L), do-not-merge, review-team-triage

#1005 Update textreadingorder.md
  windows.ui.xaml/textreadingorder.md
Labels: PRRT required, assessing_(C&L)

#1079 Add information about ShowAsMonochrome property
  windows.ui.xaml.controls/bitmapicon.md
Labels: assessing_(C&L), review-team-triage

#1166 userSecurityId must not be null
  windows.management.deployment/packagemanager_findpackagesforuser_2003648348.md
Labels: assessing_(C&L), do-not-merge, review-team-triage

#1202 [Docs] Update AppMemoryUsageLevel Enum docs to include overlimit
  windows.system/appmemoryusagelevel.md
Labels: assessing_(C&L), do-not-merge, review-team-triage

#1268 Added missing method argument to AutomationProperties.SetHeadingLevel
  windows.ui.xaml.automation/automationproperties_headinglevelproperty.md
Labels: assessing_(C&L), do-not-merge, review-team-triage

#1244 Fixed code formatting.
  windows.ui.xaml.markup/contentpropertyattribute.md
Labels: assessing_(C&L), do-not-merge, review-team-triage

#864 Update retailinfo.md
  windows.system.profile/retailinfo.md
Labels: Change sent to author, assessing_(C&L), do-not-merge

#1292 Update MainPage.xaml.cs
  windows.ui.xaml.media/code/Matrix3DProjectionSample/csharp/MainPage.xaml.cs
Labels: do-not-merge, review-team-triage
