Repository MicrosoftDocs/winrt-api, pull requests merged in 2020-03, with the labels that each got.

#1477 Fix typo
  windows.networking.backgroundtransfer/ibackgroundtransferoperation_getresponseinformation_1377125211.md
Labels: Change sent to author, do-not-merge, uwp/prod, winrt-reference/tech

#1481 Update barometer_fromidasync_1322863552.md
  windows.devices.sensors/barometer_fromidasync_1322863552.md
Labels: Change sent to author, do-not-merge, uwp/prod, winrt-reference/tech

#1478 Update downloadoperation_pause_1953642114.md
  windows.networking.backgroundtransfer/downloadoperation_pause_1953642114.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1482 Update japanesephoneticanalyzer.md
  windows.globalization/japanesephoneticanalyzer.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1480 Update windows_devices_sensors.md
  windows.devices.sensors/windows_devices_sensors.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1483 Update windows_data_json.md
  windows.data.json/windows_data_json.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1484 Update windows_globalization_collation.md
  windows.globalization.collation/windows_globalization_collation.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1500 Update isearchpanequerychangedeventargs.md
  windows.applicationmodel.search/isearchpanequerychangedeventargs.md
Labels: Change sent to author, do-not-merge, uwp/prod, winrt-reference/tech

#1504 Updating with Dispatcher clarifications.
  windows.applicationmodel.core/coreapplicationview_dispatcher.md
Labels: do-not-merge

#1475 Update link to Web authentication broker sample
  windows.security.authentication.web/webauthenticationbroker.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1501 Updated descriptions of the enums
  windows.applicationmodel/packagesignaturekind.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1506 Update chatmessagemanager_requeststoreasync_428591920.md
  windows.applicationmodel.chat/chatmessagemanager_requeststoreasync_428591920.md
Labels: Change sent to author, do-not-merge, uwp/prod, winrt-reference/tech

#1507 Fixed transpose and transverse descriptions.
  windows.storage.fileproperties/photoorientation.md
Labels: Change sent to author, do-not-merge, uwp/prod, winrt-reference/tech

#1508 Updated quickstart links to reading and writing files topic.
  windows.storage.streams/irandomaccessstream.md
  windows.storage.streams/randomaccessstream.md
Labels: Change sent to author, do-not-merge, uwp/prod, winrt-reference/tech

#1509 Fixing samples links.
  windows.storage.streams/datareader.md
  windows.storage.streams/datawriter.md
Labels: Change sent to author, do-not-merge, uwp/prod, winrt-reference/tech

#1495 Update inkworkspacehostedappmanager.md
  windows.applicationmodel.preview.inkworkspace/inkworkspacehostedappmanager.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1498 Update windows_applicationmodel_search.md
  windows.applicationmodel.search/windows_applicationmodel_search.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1519 Fixed markdown
  windows.devices.geolocation/geolocator_statuschanged.md
Labels: Change sent to author, do-not-merge, uwp/prod, winrt-reference/tech

#1525 Update windows_applicationmodel_search.md
  windows.applicationmodel.search/windows_applicationmodel_search.md
Labels: Change sent to author, do-not-merge, uwp/prod, winrt-reference/tech

#1522 Update windows_devices.md
  windows.devices/windows_devices.md
Labels: Change sent to author, do-not-merge, uwp/prod, winrt-reference/tech

#1523 Update simplehapticscontroller_stopfeedback_481424790.md
  windows.devices.haptics/simplehapticscontroller_stopfeedback_481424790.md
Labels: Change sent to author, do-not-merge, uwp/prod, winrt-reference/tech

#1526 Update webviewcontrol_capturepreviewtostreamasync_1169189879.md
  windows.web.ui.interop/webviewcontrol_capturepreviewtostreamasync_1169189879.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1529 Update iuritostreamresolver.md
  windows.web/iuritostreamresolver.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1539 Update iwebviewcontrol_cangoback.md
  windows.web.ui/iwebviewcontrol_cangoback.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1537 Update windows_web_ui.md
  windows.web.ui/windows_web_ui.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1535 Update atompubclient_maxresponsebuffersize.md
  windows.web.atompub/atompubclient_maxresponsebuffersize.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1533 Update atompubclient.md
  windows.web.atompub/atompubclient.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1531 Update windows_web_atompub.md
  windows.web.atompub/windows_web_atompub.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1516 Testing auto-assign with docfx workaround
  windows.applicationmodel/appdisplayinfo.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1520 Fix smart quotes and minor cleanup
  windows.web.ui.interop/webviewcontrol_addinitializescript_585591006.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1543 Update windows_web.md
  windows.web/windows_web.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1544 Update iuritostreamresolver.md
  windows.web/iuritostreamresolver.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1545 Update weberror_getstatus_1856274933.md
  windows.web/weberror_getstatus_1856274933.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1546 Update windows_web_http.md
  windows.web.http/windows_web_http.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1547 Update httpclient_defaultrequestheaders.md
  windows.web.http/httpclient_defaultrequestheaders.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1548 Update windows_web_ui.md
  windows.web.ui/windows_web_ui.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1549 Update iwebviewcontrol2.md
  windows.web.ui/iwebviewcontrol2.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1550 Update webviewcontrolsettings_isindexeddbenabled.md
  windows.web.ui/webviewcontrolsettings_isindexeddbenabled.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1551 Update windows_web_ui_interop.md
  windows.web.ui.interop/windows_web_ui_interop.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1552 Update webviewcontrolprocess_enterpriseid.md
  windows.web.ui.interop/webviewcontrolprocess_enterpriseid.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1553 details on directx and hardware vs. software adapters
  windows.ai.machinelearning/learningmodeldevice_learningmodeldevice_192223618.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1569 Update customxamlresourceloader_current.md
  windows.ui.xaml.resources/customxamlresourceloader_current.md
Labels: Change sent to author, do-not-merge, uwp/prod, winrt-reference/tech

#1568 Update windows_ui_xaml_resources.md
  windows.ui.xaml.resources/windows_ui_xaml_resources.md
Labels: Change sent to author, do-not-merge, uwp/prod, winrt-reference/tech

#1565 Update mapvariabledescriptorpreview_fields.md
  windows.ai.machinelearning.preview/mapvariabledescriptorpreview_fields.md
Labels: Change sent to author, do-not-merge, uwp/prod, winrt-reference/tech

#1562 Update windows_ai_machinelearning.md
  windows.ai.machinelearning/windows_ai_machinelearning.md
Labels: Change sent to author, do-not-merge, uwp/prod, winrt-reference/tech

#1571 Clarify remarks and add example
  windows.ui.xaml.controls/autosuggestbox_suggestionchosen.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1574 Add info to typeMetadata parameter
  windows.ui.xaml/dependencyproperty_register_1826645607.md
Labels: Change sent to author, do-not-merge, uwp/prod, winrt-reference/tech
