Repository MicrosoftDocs/winrt-api, pull requests merged in 2020-12, with the labels that each got.

#1877 [ItemPanel] Clarify it's important to use the correct StackPanel type
  windows.ui.xaml.controls/itemscontrol_itemspanel.md
Labels: Change sent to author, aq-pr-triaged, ready-to-merge, uwp/prod, winrt-reference/tech

#1895 precision of the symbol *.
  windows.ui.xaml.controls/grid_rowdefinitions.md
Labels: Change sent to author, aq-pr-triaged, ready-to-merge, uwp/prod, winrt-reference/tech

#1900 Update asyncactioncompletedhandler.md
  windows.foundation/asyncactioncompletedhandler.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1903 grammer fix
  windows.devices.alljoyn/alljoynaboutdata_softwareversion.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1906 Misspelling in description
  windows.devices.bluetooth.genericattributeprofile/gattdeviceservice_getcharacteristicsasync_652132649.md
Labels: do-not-merge, review-team-triage

#1907 @abrgg Misspelling in description
  windows.devices.bluetooth.genericattributeprofile/gattdeviceservice_getcharacteristicsasync_1845166286.md
Labels: do-not-merge, review-team-triage
