Repository MicrosoftDocs/winrt-api, pull requests merged in 2020-10, with the labels that each got.

#1845 Update focusmanager_tryfocusasync_1779533284.md
  windows.ui.xaml.input/focusmanager_tryfocusasync_1779533284.md
Labels: Change sent to author, do-not-merge, uwp/prod, winrt-reference/tech

#1851 Update displaymonitor_isdolbyvisionsupportedinhdrmode.md
  windows.devices.display/displaymonitor_isdolbyvisionsupportedinhdrmode.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1846 AppInstance cache -> store
  windows.applicationmodel/appinstance.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1863 Link most drag & drop APIs to the UWP drag & drop overview
  windows.ui.xaml.controls/listviewbase_canreorderitems.md
  windows.ui.xaml/uielement_allowdrop.md
  windows.ui.xaml/uielement_candrag.md
  windows.ui.xaml/uielement_dragover.md
  windows.ui.xaml/uielement_drop.md
  windows.ui.xaml/uielement_dropevent.md
Labels: Change sent to author, aq-pr-triaged, ready-to-merge, uwp/prod, winrt-reference/tech

#1864 docs: the property should be in CamelCase
  windows.storage/applicationdata_current.md
Labels: Change sent to author, do-not-merge, uwp/prod, winrt-reference/tech
