Repository MicrosoftDocs/winrt-api, pull requests merged in 2020-01, with the labels that each got.

#1378 Update itemscontrol_itemssource.md
  windows.ui.xaml.controls/itemscontrol_itemssource.md
Labels: Change sent to author, assessing_(C&L), do-not-merge, uwp/prod, winrt-reference/tech

#1376 MenuFlyout.Items can never be null
  windows.ui.xaml.controls/menuflyout_items.md
Labels: Change sent to author, assessing_(C&L), do-not-merge, uwp/prod, winrt-reference/tech

#1387 Fix typo in statusbar.md
  windows.ui.viewmanagement/statusbar.md
Labels: Change sent to author, do-not-merge, uwp/prod, winrt-reference/tech

#1389 Added more details and examples to ItemContainerStyle API doc
  windows.ui.xaml.controls/images/itemcontainerstyle-snapshot.png
  windows.ui.xaml.controls/itemscontrol_itemcontainerstyle.md
Labels: Change sent to author, do-not-merge, uwp/prod, winrt-reference/tech

#1392 Remove winui tech from the Windows.UI.** namespace
  docfx.json
Labels: do-not-merge, review-team-triage

#1362 Fix the example of ManipulationDelta.Scale
  windows.ui.input/manipulationdelta.md
Labels: Change sent to author, assessing_(C&L), do-not-merge, uwp/prod, winrt-reference/tech

#1398 Update mapmodel3d.md
  windows.ui.xaml.controls.maps/mapmodel3d.md
Labels: Change sent to author, assessing_(C&L), do-not-merge, uwp/prod, winrt-reference/tech

#1397 Update mapmodel3d_mapmodel3d_1221375020.md
  windows.ui.xaml.controls.maps/mapmodel3d_mapmodel3d_1221375020.md
Labels: Change sent to author, assessing_(C&L), uwp/prod, winrt-reference/tech

#1408 Update holdingroutedeventargs_getposition_1813281865.md
  windows.ui.xaml.input/holdingroutedeventargs_getposition_1813281865.md
Labels: Change sent to author, assessing_(C&L), do-not-merge, uwp/prod, winrt-reference/tech

#1419 Fix typos and formatting issues.
  windows.ui.xaml.controls.primitives/togglebutton_ischecked.md
Labels: Change sent to author, do-not-merge, uwp/prod, winrt-reference/tech

#1386 Update sample code to remove incorrect variable
  windows.ui.xaml/dependencyobject_registerpropertychangedcallback_1557279748.md
Labels: Change sent to author, assessing_(C&L), do-not-merge, uwp/prod, winrt-reference/tech

#1413 Add file contents to FileSavePicker JavaScript example
  windows.storage.pickers/code/FilePicker/js/js/scenario4.js
Labels: assessing_(C&L), do-not-merge, review-team-triage
