Repository MicrosoftDocs/winrt-api, pull requests merged in 2020-11, with the labels that each got.

#1867 [ListViewAutomationPeer] Update list of peers to be easier to understand
  windows.ui.xaml.automation.peers/listviewautomationpeer.md
Labels: Change sent to author, ready-to-merge, uwp/prod, winrt-reference/tech

#1869 Update usbdevice.md
  windows.devices.usb/usbdevice.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1873 Update idirect3dsurface.md
  windows.graphics.directx.direct3d11/idirect3dsurface.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1876 Fix markdown in ApplicationExecutionState
  windows.applicationmodel.activation/applicationexecutionstate.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1874 document null return case from User::GetPictureAsync()
  windows.system/user_getpictureasync_2117608675.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1890 Wilson ng007 patch 1
  windows.applicationmodel.calls/phoneline_id.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, review-team-triage, windows/prod

#1891 Corrected description of the Value of ExposureControl
  windows.media.devices/exposurecontrol_max.md
  windows.media.devices/exposurecontrol_min.md
  windows.media.devices/exposurecontrol_value.md
Labels: Change sent to author, do-not-merge, uwp/prod, winrt-reference/tech
