Repository MicrosoftDocs/winrt-api, pull requests merged in 2020-02, with the labels that each got.

#1423 Added link to sample code: ListViewBase.ScrollIntoView
  windows.ui.xaml.controls/listviewbase_scrollintoview_2024050476.md
Labels: Change sent to author, assessing_(C&L), do-not-merge, uwp/prod, winrt-reference/tech

#1440 Update statusbar.md
  windows.ui.viewmanagement/statusbar.md
Labels: Change sent to author, do-not-merge, uwp/prod, winrt-reference/tech

#1442 Add reference to CreateDispatcherQueueController API
  windows.system/dispatcherqueuecontroller.md
Labels: assessing_(C&L), do-not-merge, uwp/prod, winrt-reference/tech

#1448 Update rfcommserviceprovider_createasync_725413930.md
  windows.devices.bluetooth.rfcomm/rfcommserviceprovider_createasync_725413930.md
Labels: Change sent to author, assessing_(C&L), do-not-merge, uwp/prod, winrt-reference/tech

#1449 Explain Foreground property restrictions
  windows.ui.xaml.controls/bitmapicon.md
Labels: Change sent to author, assessing_(C&L), do-not-merge, uwp/prod, winrt-reference/tech

#1456 Remove duplicate content.
  windows.ui.popups/popupmenu_commands.md
Labels: Change sent to author, do-not-merge, uwp/prod, winrt-reference/tech

#1453 Update radialcontrollerbuttonpressedeventargs.md
  windows.ui.input/radialcontrollerbuttonpressedeventargs.md
Labels: Change sent to author, assessing_(C&L), do-not-merge, uwp/prod, winrt-reference/tech

#1458 Mention limited support for Variants
  windows.ui.xaml/fontvariants.md
Labels: Change sent to author, assessing_(C&L), do-not-merge, uwp/prod, winrt-reference/tech

#1465 Update windows_devices_sensors.md
  windows.devices.sensors/windows_devices_sensors.md
Labels: Change sent to author, do-not-merge, uwp/prod, winrt-reference/tech

#1468 Update windows_devices_sensors.md
  windows.devices.sensors/windows_devices_sensors.md
Labels: Change sent to author, do-not-merge, uwp/prod, winrt-reference/tech

#1455 Clarify documenation for MediaFrameReference intrinsics and extrinsics
  windows.media.devices.core/cameraintrinsics_principalpoint.md
  windows.media.devices.core/cameraintrinsics_projectmanyontoframe_706628651.md
  windows.media.devices.core/cameraintrinsics_projectontoframe_368534707.md
  windows.media.devices.core/cameraintrinsics_undistortedprojectiontransform.md
  windows.media.devices.core/cameraintrinsics_unprojectatunitdepth_1064040166.md
  windows.media.devices.core/cameraintrinsics_unprojectpixelsatunitdepth_1708320502.md
Labels: Change sent to author, assessing_(C&L), do-not-merge, uwp/prod, winrt-reference/tech

#1464 See UIElement property for more info
  windows.ui.xaml/application_highcontrastadjustment.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1463 Update threading description
  windows.ui.xaml/window_current.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1441 Add reference to DispatcherQueueController
  windows.system/dispatcherqueue.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1439 remove contradicting info
  windows.ui.composition/compositionsurfacebrush_horizontalalignmentratio.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1438 important info missing
  windows.ui.composition/compositiongradientbrush.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1437 important info missing
  windows.ui.composition/compositionviewbox_verticalalignmentratio.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1470 Update windows_devices_sensors.md
  windows.devices.sensors/windows_devices_sensors.md
Labels: Change sent to author, do-not-merge, uwp/prod, winrt-reference/tech

#1302 Fix DirectX11 example in iframeworkview.md
  windows.applicationmodel.core/iframeworkview.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1321 Update Vpn Package Family Name to note required field and add helpful remark
  windows.networking.vpn/vpnpluginprofile_vpnpluginpackagefamilyname.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech
