Repository MicrosoftDocs/winrt-api, pull requests merged in 2020-05, with the labels that each got.

#1628 Added RadialGradientBrush links to LinearGradientBrush and GradientBrush
  windows.ui.xaml.media/gradientbrush.md
  windows.ui.xaml.media/lineargradientbrush.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1632 Document interpretation of axis-angle quantities
  windows.perception.spatial/spatiallocation_absoluteangularaccelerationaxisangle.md
  windows.perception.spatial/spatiallocation_absoluteangularvelocityaxisangle.md
  windows.perception.spatial/spatiallocation_absolutelinearacceleration.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1656 Add links from WinRT Display.Core APIs to their COM interop interfaces
  windows.devices.display.core/displaydevice.md
  windows.devices.display.core/displaypath.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1665 Typo
  windows.applicationmodel.store.preview.installcontrol/appinstallmanager_startappinstallasync_1749232586.md
Labels: do-not-merge, review-team-triage

#1662 Windows.ApplicationModel.Calls main page: Update links to archived samples
  windows.applicationmodel.calls/windows_applicationmodel_calls.md
Labels: aq-pr-triaged, do-not-merge, review-team-triage, windows/prod, windows/svc
