Repository MicrosoftDocs/winrt-api, pull requests merged in 2021-04, with the labels that each got.

#1978 add a link to the policy names
  windows.management.policies/namedpolicy.md
Labels: Change sent to author, aq-pr-triaged, ready-to-merge, uwp/prod, winrt-reference/tech

#1985 Remove InkPresenter note from the InkCanvas API page
  windows.ui.xaml.controls/inkcanvas.md
Labels: Change sent to author, do-not-merge, uwp/prod, winrt-reference/tech

#1986 Update rectint32.md to update the documentation of the fields of RectInt32 Struct
  windows.graphics/rectint32.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech

#1984 Fix LaunchFileAsync C# example
  windows.system/launcher_launchfileasync_1594978114.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech
