Repository MicrosoftDocs/winrt-api, pull requests merged in 2021-02, with the labels that each got.

#1934 Fixes formatting of bullet list
  windows.foundation/uri.md
Labels: Change sent to author, do-not-merge, uwp/prod, winrt-reference/tech

#1939 Updating Windows version for known issues.
  windows.ui.composition/pathkeyframeanimation.md
Labels: Change sent to author, aq-pr-triaged, doc-bug, ready-to-merge

#1941 Update windows_networking_vpn.md
  windows.networking.vpn/windows_networking_vpn.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, uwp/prod, winrt-reference/tech
