Repository MicrosoftDocs/winrt-api, pull requests merged in 2021-01, with the labels that each got.

#1912 FlashControl.Auto now accurately describes how it affects the focus assist light
  windows.media.devices/flashcontrol_assistantlightenabled.md
  windows.media.devices/flashcontrol_auto.md
Labels: Change sent to author, aq-pr-triaged, do-not-merge, doc-enhancement, review-team-triage

#1917 This is how you temp kill a bot.
  .config/merlinbot/reviewrecommender.yaml
Labels: Change sent to author, aq-pr-triaged, assigned-to-author, do-not-merge, unspecified/svc

#1924 Small little typo fixed.
  windows.devices.gpio/gpiopin_valuechanged.md
Labels: Change sent to author, do-not-merge, uwp/prod, winrt-reference/tech

#1926 Fix link in Button class page
  windows.ui.xaml.controls/button.md
Labels: Change sent to author, do-not-merge, uwp/prod, winrt-reference/tech

#1930 Fix minor typo
  windows.management.deployment/packagemanager_provisionpackageforallusersasync_653384863.md
Labels: Change sent to author, do-not-merge, uwp/prod, winrt-reference/tech

#1932 Update windows_devices_display_core.md
  windows.devices.display.core/windows_devices_display_core.md
Labels: Change sent to author, do-not-merge, uwp/prod, winrt-reference/tech
