Repository MicrosoftDocs/winrt-api, pull requests merged in 2022-06, with the labels that each got.

#2191 Update passwordvault.md
  windows.security.credentials/passwordvault.md
Labels: Change sent to author, do-not-merge, aq-pr-triaged, winrt-reference/tech, uwp/prod

#2244 Update dataproviderrequest_getdeferral_254836512.md
  windows.applicationmodel.datatransfer/dataproviderrequest_getdeferral_254836512.md
Labels: Change sent to author, ready-to-merge, winrt-reference/tech, uwp/prod

#2242 Update corephysicalkeystatus.md
  windows.ui.core/corephysicalkeystatus.md
Labels: Change sent to author, do-not-merge, aq-pr-triaged, winrt-reference/tech, uwp/prod

#2248 Update characterreceivedroutedeventargs_character.md
  windows.ui.xaml.input/characterreceivedroutedeventargs_character.md
Labels: Change sent to author, do-not-merge, winrt-reference/tech, uwp/prod

#2234 Remove unneeded usage note
  windows.ui.input.inking/inkpresenter.md
Labels: Change sent to author, do-not-merge, aq-pr-triaged, winrt-reference/tech, uwp/prod

#2247 Update virtualkey.md
  windows.system/virtualkey.md
Labels: Change sent to author, do-not-merge, review-team-triage, aq-pr-triaged, winrt-reference/tech, uwp/prod
