Repository MicrosoftDocs/winrt-api, pull requests merged in 2022-11, with the labels that each got.

#2298 Fix typo on Treeview.HasUnrealizedChildren property
  windows.ui.xaml.controls/treeviewnode_hasunrealizedchildren.md
Labels: Change sent to author, do-not-merge, aq-pr-triaged, winrt-reference/tech, uwp/prod

#2118 Update webaccount_getpictureasync_202157661.md
  windows.security.credentials/webaccount_getpictureasync_202157661.md
Labels: Change sent to author, do-not-merge, review-team-triage, aq-pr-triaged, winrt-reference/tech, uwp/prod

#2300 Update inputscopenamevalue.md for a Policheck issue
  windows.ui.xaml.input/inputscopenamevalue.md
Labels: Change sent to author, do-not-merge, winrt-reference/tech, uwp/prod

#2305 Update storageitemmostrecentlyusedlist.md
  windows.storage.accesscache/storageitemmostrecentlyusedlist.md
Labels: Change sent to author, do-not-merge, winrt-reference/tech, uwp/prod

#2302 Update namedpolicy_getpolicyfrompathforuser_519375791.md
  windows.management.policies/namedpolicy_getpolicyfrompathforuser_519375791.md
Labels: Change sent to author, do-not-merge, aq-pr-triaged, winrt-reference/tech, uwp/prod
