Repository MicrosoftDocs/winrt-api, pull requests merged in 2022-09, with the labels that each got.

#2285 Typo in AlternateWordForm
  windows.data.text/alternatewordform.md
Labels: Change sent to author, do-not-merge, winrt-reference/tech, uwp/prod

#2287 Update storagefilequeryresult_getfilesasync_1261374131.md
  windows.storage.search/storagefilequeryresult_getfilesasync_1261374131.md
Labels: Change sent to author, do-not-merge, winrt-reference/tech, uwp/prod

#2246 Update virtualkeymodifiers.md
  windows.system/virtualkeymodifiers.md
Labels: Change sent to author, do-not-merge, aq-pr-triaged, winrt-reference/tech, uwp/prod

#2291 Fixed typo
  windows.storage.pickers/filesavepicker.md
Labels: Change sent to author, do-not-merge, winrt-reference/tech, uwp/prod

#2292 Update uielementcollection_append_1858337955.md
  windows.ui.xaml.controls/uielementcollection_append_1858337955.md
Labels: Change sent to author, ready-to-merge, aq-pr-triaged, winrt-reference/tech, uwp/prod
