Repository MicrosoftDocs/winrt-api, pull requests merged in 2022-02, with the labels that each got.

#2146 Update itemcollection_size.md
  windows.ui.xaml.controls/itemcollection_size.md
Labels: Change sent to author, ready-to-merge, aq-pr-triaged, winrt-reference/tech, uwp/prod

#2147 Update popupmenu.md
  windows.ui.popups/popupmenu.md
Labels: Change sent to author, do-not-merge, aq-pr-triaged, winrt-reference/tech, uwp/prod

#2138 Update threadingattribute.md
  windows.foundation.metadata/threadingattribute.md
Labels: Change sent to author, do-not-merge, aq-pr-triaged, winrt-reference/tech, uwp/prod

#2121 Fix InstalledDesktopApp.GetInventoryAsync example
  windows.system.inventory/installeddesktopapp.md
  windows.system.inventory/installeddesktopapp_getinventoryasync_1556611742.md
Labels: Change sent to author, do-not-merge, aq-pr-triaged, winrt-reference/tech, uwp/prod

#2114 Update iclosable_close_811482585.md
  windows.foundation/iclosable_close_811482585.md
Labels: Change sent to author, do-not-merge, aq-pr-triaged, winrt-reference/tech, uwp/prod

#2141 Update coreapplication.md
  windows.applicationmodel.core/coreapplication.md
Labels: Change sent to author, do-not-merge, aq-pr-triaged, winrt-reference/tech, uwp/prod

#2023 Update windows_applicationmodel.md
  windows.applicationmodel/windows_applicationmodel.md
Labels: Change sent to author, do-not-merge, aq-pr-triaged, winrt-reference/tech, uwp/prod

#2018 Update fulltrustprocesslauncher.md
  windows.applicationmodel/fulltrustprocesslauncher.md
Labels: Change sent to author, do-not-merge, aq-pr-triaged, winrt-reference/tech, uwp/prod

#2166 Update compositioneasingfunction.md
  windows.ui.composition/compositioneasingfunction.md
Labels: Change sent to author, ready-to-merge, aq-pr-triaged, winrt-reference/tech, uwp/prod

#2144 Update colorhelper_fromargb_1449236110.md
  windows.ui/colorhelper_fromargb_1449236110.md
Labels: Change sent to author, ready-to-merge, aq-pr-triaged, winrt-reference/tech, uwp/prod

#2181 Update deferralcompletedhandler.md
  windows.foundation/deferralcompletedhandler.md
Labels: Change sent to author, do-not-merge, winrt-reference/tech, uwp/prod
