Repository MicrosoftDocs/winrt-api, pull requests merged in 2022-04, with the labels that each got.

#2204 Update audioencodingproperties.md
  windows.media.mediaproperties/audioencodingproperties.md
Labels: Change sent to author, do-not-merge, winrt-reference/tech, uwp/prod

#2203 Update audioeffect.md
  windows.media.effects/audioeffect.md
Labels: Change sent to author, do-not-merge, aq-pr-triaged, winrt-reference/tech, uwp/prod

#2207 Update jumplist_items.md
  windows.ui.startscreen/jumplist_items.md
Labels: Change sent to author, winrt-reference/tech, uwp/prod

#2196 Pointer to AccountSettingsPaneInterop class
  windows.ui.applicationsettings/accountssettingspane.md
Labels: Change sent to author, ready-to-merge, aq-pr-triaged, winrt-reference/tech, uwp/prod

#2208 Update the notice in the MessageDialog documentation to be technically correct
  windows.ui.popups/messagedialog.md
Labels: Change sent to author, do-not-merge, aq-pr-triaged, winrt-reference/tech, uwp/prod

#2066 Update iclosable_close_811482585.md
  windows.foundation/iclosable_close_811482585.md
Labels: Change sent to author, do-not-merge, aq-pr-triaged, winrt-reference/tech, uwp/prod

#2213 clarify the socket restrictions: they only apply to this method
  windows.networking.vpn/vpnchannel_associatetransport_841671883.md
Labels: Change sent to author, do-not-merge, winrt-reference/tech, uwp/prod

#2212 Remove the documented restrictions on the socket types
  windows.networking.vpn/vpnchannel_replaceandassociatetransport_1938622656.md
Labels: Change sent to author, do-not-merge, winrt-reference/tech, uwp/prod

#2211 Removed old restriction on socket types.
  windows.networking.vpn/vpnchannel_addandassociatetransport_1590467618.md
Labels: Change sent to author, do-not-merge, aq-pr-triaged, winrt-reference/tech, uwp/prod
