Repository MicrosoftDocs/winrt-api, pull requests merged in 2023-01, with the labels that each got.

#2320 Update packagesignaturekind.md
  windows.applicationmodel/packagesignaturekind.md
Labels: Change sent to author, do-not-merge, winrt-reference/tech, uwp/prod

#2322 create .openpublishing.publish.config
  .openpublishing.publish.config.json
Labels: do-not-merge, review-team-triage

#2324 update-build-source-folder-in-config.json
  .openpublishing.publish.config.json
Labels: do-not-merge, review-team-triage

#2323 Update keyboardcapabilities.md
  windows.devices.input/keyboardcapabilities.md
Labels: Change sent to author, do-not-merge, winrt-reference/tech, uwp/prod

#2325 Update crossslidethresholds.md
  windows.ui.input/crossslidethresholds.md
Labels: Change sent to author, do-not-merge, winrt-reference/tech, uwp/prod

#2326 Update .openpublishing.publish.config.json
  .openpublishing.publish.config.json
Labels: Change sent to author, do-not-merge, aq-pr-triaged, docs-editor-pilot

#2328 Update edgegesturekind.md
  windows.ui.input/edgegesturekind.md
Labels: Change sent to author, do-not-merge, aq-pr-triaged, winrt-reference/tech, uwp/prod

#2327 Update crossslidingstate.md
  windows.ui.input/crossslidingstate.md
Labels: Change sent to author, do-not-merge, aq-pr-triaged, winrt-reference/tech, uwp/prod

#2331 Add a note that "Copy link" is not a share for DataPackage
  windows.applicationmodel.datatransfer/datapackage_sharecompleted.md
Labels: Change sent to author, do-not-merge, winrt-reference/tech, uwp/prod
